### ISSUE TITLE
`DaggerViewModelInjector` Unresolved reference

### ISSUE THREAD

**Issue by lhoyong** [gahfy/MVVMPosts#3]
hi, i try your [example](https://proandroiddev.com/mvvm-with-kotlin-android-architecture-components-dagger-2-retrofit-and-rxandroid-1a4ebb38c699) , but i can't find `DaggerViewModelInjector`

how to get this code?

**Comment by gahfy** [comment]
You have to build the app (Android Studio, Menu Build => Rebuild Project). This class is generated

**Comment by lhoyong** [comment]
you r right. thanks!

**Comment by gahfy** [comment]
OK, I mark the issue as closed then

**Comment by mehrdaddolatkhah** [comment]
Hi, I did rebuild and clean project but still I have this issue dear @gahfy
